### ISSUE TITLE
Bra and ket conjugated incorrectly in recent commits

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [QuantumKitHub/PEPSKit.jl#109]
The current master branch mistakably conjugated kets (and bras are not) in several places of `ctmrg_contractions.jl`: (discovered by @Sander-De-Meyer)

https://github.com/QuantumKitHub/PEPSKit.jl/blob/3158c044603ef7b5915d56c5af9f83eb3366995e/src/algorithms/contractions/ctmrg_contractions.jl#L344-L347

https://github.com/QuantumKitHub/PEPSKit.jl/blob/3158c044603ef7b5915d56c5af9f83eb3366995e/src/algorithms/contractions/ctmrg_contractions.jl#L916

In addition, for the following function:

https://github.com/QuantumKitHub/PEPSKit.jl/blob/3158c044603ef7b5915d56c5af9f83eb3366995e/src/algorithms/contractions/ctmrg_contractions.jl#L189-L210

The indices don't match. @pbrehmer Could you please make a more thorough check of recently added code to make sure there are no more similar mistakes?

**Comment by pbrehmer** [comment]
Oh no, my bad! I'll fix the wrong `conj` and the index mismatch. However, the first example in line 344 is the action of the *adjoint* half-infinite environment on a vector `x`. (This is used by iterative SVDs that only take a function handle.) So in that case the `conj` has to act on the ket instead of the bra, I believe.
