### ISSUE TITLE
Question : How does CTMRG work together with symmetric tensors ?

### ISSUE THREAD

**Issue by Gertian** [QuantumKitHub/PEPSKit.jl#64]
Hi,

I was trying to run some PEPS numerics for a model with SU(N)*U(1)*FermionZ2 symmetry. 

To do this I implemented the Hamiltonian with minimal symmetry (i.e. only the fermionic Z2) and with all symmetries. I then noticed that the less symmetric implementation _heavily_ outperforms the more symmetric implementation. 

For starters the CTMRG environments fail to converge in the symmetric case since the error remained INF at all times. According to Lukas this means that new sectors are being added but after some time I'd expect some form of convergence ? Does anybody know why this might not happen ?

After forcing the environment bonds to remain constant I get convergence but still I get the usual (i.e. MPS) behavior that small bond dimensions without symmetries yield lower energies then the corresponding bond dimension with symmetries. 

In general it seems that enforcing symmetries seems to be a less effective tool for PEPS then MPS. Did anybody already think about this in a more structured manner ? If so, I'd love to hear your cup of tea on this.

**Comment by lkdvos** [comment]
I think what you are describing is indeed the expected behaviour, imposing symmetry restricts the variational manifold, such that the energies are higher. The flipside is that the actual physics might be closer to the thing you want to simulate, since you are not breaking the symmetry just to obtain lower energies, if you expect the symmetry to be unbroken.

Also keep in mind that in 2D, there are no LSM-type arguments for continuous symmetries to remain unbroken, so depending on the model you are trying to simulate, it might just be the case that imposing the symmetry is not what you want to do at all.

Finally, the `Inf` error is mostly just a matter of how we compute the error, so we could look into altering this. For symmetries, the problem becomes larger, as the spectrum can shift quite drastically depending on how you cut, for each sector separately, such that getting this to stabilize is somewhat difficult.
However, I would expect if you want a performant algorithm, it really is best to use the `FixedSpaceTruncation`. You could just do one run in the beginning that attempts to fix the environment virtual spaces, and then keep this fixed for a while. (This is probably even the case without symmetries)

**Comment by Gertian** [comment]
Ok, thanks for this information. 

I found it interesting that this seems to be so much worse for PEPS as for MPS though. Is is somehow harder to add the right sectors for PEPS ?

**Comment by lkdvos** [comment]
I guess doing CTMRG with changing sectors each iteration is like doing two-site update schemes in MPS, with even more degrees of freedom, which is already for MPS not super stable. The fact that there is no canonical form also makes this kind of hard, and truncating loopy networks is not as easy as MPS, so yes, PEPS is harder :wink:

**Comment by Gertian** [comment]
Thanks for this very clarifying answer (as always) !
